import type { Metadata } from "next";
import { Montserrat, Karla } from "next/font/google";
import Header from "@/components/modules/Header/Header";
import Footer from "@/components/modules/Footer/Footer";
import SubscribeCta from "@/components/sections/Newsletter";
import "@/assets/scss/main.scss";

const primary = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const accent = Karla({ subsets: ["latin"], variable: "--font-karla" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${primary.variable} ${accent.variable}`}>
        <Header />
        <main className="main">{children}</main>
        <SubscribeCta />
        <Footer />
      </body>
    </html>
  );
}
